apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-sapjvm
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world-sapjvm
    spec:
      containers:
      - name: hello-world-pod-sapjvm
        resources:
          limits:
            cpu: "2.5"
          requests:
            cpu: "1"
        image: cristianpopa/sapjvm:latest
       
        ports: 
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: private-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-sapjvm
spec:
  selector:
    app: hello-world-sapjvm
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
