apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-oraclejvm
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world-oraclejvm
    spec:
      containers:
      - name: hello-world-pod-oraclejvm
        resources:
          limits:
            cpu: "2.5"
          requests:
            cpu: "1"
        image: cristianpopa/sapjvm:oracle
       
        ports: 
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: private-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-oraclejvm
spec:
  selector:
    app: hello-world-oraclejvm
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
