apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-alpine
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world-alpine
    spec:
      containers:
      - name: hello-world-pod-alpine
        resources:
          limits:
            cpu: "2.5"
          requests:
            cpu: "1"
        image: cristianpopa/cpucountjava-alpine:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-alpine
spec:
  selector:
    app: hello-world-alpine
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
